Replace error when tree = FALSE and serial specified with a warning.
epiverse-trace/bpmodels pull request #20
Opened 2023-01-16 17:09 UTC by jamesmbaazam

Instead of an error, the user will now be warned that `tree` was set to `TRUE` for them because they *probably* mistakenly specified `tree=FALSE` with `serial` also specified. This will address #16.

2023-01-18 15:54 UTC, sbfnk reviewed
Looks good to me - as does the vignette. Is that supposed to be in this pull request? If yes then I think it would [better fit](https://r-pkgs.org/vignettes.html) in a `vignettes` directory.

2023-01-18 16:35 UTC, jamesmbaazam commented on R/simulate.r
> +          }
The vignettes are in the /vignettes directory.

2023-01-18 16:39 UTC, jamesmbaazam commented on doc/introduction.Rmd
> +chain_ll(chain_sizes, "pois", "size", lambda=0.5)
I prefer the spaces too and use the `styler` package addin to fix them automatically. These are from the original code and have mostly been fixed in the first PR.

2023-01-18 16:41 UTC, jamesmbaazam commented on doc/introduction.Rmd
> +# References
That's also being addressed elsewhere on the "vignettes" branch.

2023-01-19 14:27 UTC, sbfnk requested changes
Vignette in `doc/` should be removed as in a forthcoming PR.

2023-01-27 11:15 UTC, merged